language: python
# command to install dependencies
install:
  - pip install pytest pytest-cov coverage numpydoc  # for testing
  - pip install flake8 check-manifest codecov
  - pip install -e .
script:
  - pytest -lv --cov-report term-missing gsroptim --cov=gsroptim --cov-config .coveragerc
  - flake8 --count gsroptim
after_success:
  - codecov